// ============================================================
// src/lib/utils.ts
// Shared utility functions
// ============================================================

import { type ClassValue, clsx } from "clsx";
import type { SavedReport, ScoreBand } from "@/types";
import { getScoreLabel } from "@/types";
import { format } from "date-fns";

/** Merge Tailwind class names conditionally */
export function cn(...inputs: ClassValue[]) {
  return clsx(inputs);
}

/** Format a date string for display */
export function formatDate(isoString: string): string {
  try {
    return format(new Date(isoString), "MMM d, yyyy · h:mm a");
  } catch {
    return isoString;
  }
}

/** Returns Tailwind color classes based on score band */
export function getScoreColors(band: ScoreBand): {
  bg: string;
  text: string;
  border: string;
  badge: string;
} {
  switch (band) {
    case "strong":
      return {
        bg: "bg-emerald-50",
        text: "text-emerald-700",
        border: "border-emerald-200",
        badge: "bg-emerald-100 text-emerald-700",
      };
    case "moderate":
      return {
        bg: "bg-amber-50",
        text: "text-amber-700",
        border: "border-amber-200",
        badge: "bg-amber-100 text-amber-700",
      };
    case "weak":
      return {
        bg: "bg-red-50",
        text: "text-red-700",
        border: "border-red-200",
        badge: "bg-red-100 text-red-700",
      };
  }
}

/** Download a SavedReport as a formatted JSON file */
export function downloadReportJSON(report: SavedReport): void {
  const exportData = {
    exportedAt: new Date().toISOString(),
    appName: "MarketLens",
    report: {
      id: report.id,
      createdAt: report.created_at,
      businessIdea: report.niche,
      location: report.location,
      targetCustomer: report.target_customer,
      productType: report.product_type,
      priceRange: report.price_range,
      competitors: report.competitors_input,
      analysis: report.report_data,
    },
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], {
    type: "application/json",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `marketlens-${report.niche.toLowerCase().replace(/\s+/g, "-")}-${
    report.id.slice(0, 8)
  }.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Build a plain-text version of the report for copying to clipboard */
export function buildReportText(report: SavedReport): string {
  const d = report.report_data;
  const lines: string[] = [
    "═══════════════════════════════════════════════",
    "  MARKETLENS — MARKET INTELLIGENCE REPORT",
    "═══════════════════════════════════════════════",
    `Business: ${report.niche}`,
    `Location: ${report.location}`,
    `Target Customer: ${report.target_customer}`,
    `Generated: ${formatDate(report.created_at)}`,
    "",
    `MARKET OPPORTUNITY SCORE: ${d.marketScore}/100 — ${getScoreLabel(d.marketScore)}`,
    "",
    "── EXECUTIVE SUMMARY ──────────────────────────",
    d.summary,
    "",
    "── TARGET CUSTOMER PROFILE ────────────────────",
    d.targetCustomer,
    "",
    "── PRICING RECOMMENDATION ─────────────────────",
    d.pricingRecommendation,
    "",
    "── CUSTOMER PAIN POINTS ───────────────────────",
    ...(d.customerPainPoints ?? []).map((p, i) => `${i + 1}. ${p}`),
    "",
    "── DEMAND TREND ───────────────────────────────",
    d.demandTrend,
    "",
    "── DIFFERENTIATION STRATEGY ───────────────────",
    d.differentiationStrategy,
    "",
    "── MARKETING CHANNELS ─────────────────────────",
    ...(d.marketingChannels ?? []).map((c) => `• ${c}`),
    "",
    "── RISKS & WEAKNESSES ─────────────────────────",
    ...(d.risks ?? []).map((r) => `⚠ ${r}`),
    "",
    "── ACTION PLAN ────────────────────────────────",
    ...(d.actionPlan ?? []).map((a, i) => `${i + 1}. ${a}`),
    "",
    "── COMPETITOR TABLE ───────────────────────────",
    ...(d.competitorTable ?? []).map(
      (c) =>
        `${c.name} | ${c.estimatedPriceRange}\n   Strength: ${c.strength}\n   Weakness: ${c.weakness}`
    ),
    "",
    "═══════════════════════════════════════════════",
    "  Generated by MarketLens — marketlens.app",
    "═══════════════════════════════════════════════",
  ];

  return lines.join("\n");
}

/** Truncate a string to maxLen characters with ellipsis */
export function truncate(str: string, maxLen = 120): string {
  if (str.length <= maxLen) return str;
  return str.slice(0, maxLen).trimEnd() + "…";
}
